model:
  source: ".model/"
max_context_length: 16384
stop_tokens:
  - "</s>"
prompt_format:
  chat:
    system: "SYSTEM: {}\n"
    assistant: "ASSISTANT: {}\n"
    user: "USER: {}\n"
defaults:
  top_p: 1.0
  top_k: 0