apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    zarf.dev/connect-description: "###ZARF_CONST_NAME### gRPC endpoint."
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    zarf.dev/connect-name: "###ZARF_CONST_NAME###"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
