apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-backend-configmap
data:
  LAI_HF_HUB_ENABLE_HF_TRANSFER: "1"
  LAI_REPO_ID: "TheBloke/Synthia-7B-v2.0-GPTQ"
  LAI_REVISION: "gptq-4bit-32g-actorder_True"
  LAI_QUANTIZATION: "gptq"