name: Release Artifacts

on:
  push:
    tags:
      - "*.*.*"
      - dev
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ai-ubuntu-big-boy-4-core
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Version
        id: get_version
        uses: battila7/get-version-action@90eb8fc70f6dfcf3f9b95ed8f164d2c05038e729 # v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          make docker-build docker-push VERSION=${{ steps.get_version.outputs.version-without-v }}

  zarf-publish:
    runs-on: ai-ubuntu-big-boy-4-core
    needs: docker-publish
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Version
        id: get_version
        uses: battila7/get-version-action@90eb8fc70f6dfcf3f9b95ed8f164d2c05038e729 # v2.2.1

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@f95763914e20e493bb5d45d63e30e17138f981d6 # v1.0.0

      - name: Build Zarf Package
        run: zarf package create . --set=PACKAGE_VERSION=${{ steps.get_version.outputs.version-without-v }} --set=IMAGE_VERSION=${{ steps.get_version.outputs.version-without-v }} --confirm

      - name: Publish Zarf Package
        run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages/leapfrogai